---
langs: [fr_FR,en_US,de_DE,es_ES,id_ID] 
baseurl: "/"
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- vendor
plugins:
- jekyll-seo-tag
title: "Documentation NextDom"
description: "Ceci est la documentation du plugin de la team NextDom"
author: "Jeedom-Plugins-Extra"
image: https://avatars1.githubusercontent.com/u/36200380?s=200&v=4
social:
  name: NextDom
  links:
    - https://github.com/NextDom
